🌱 Adding Github Action to verify title
operator-framework/audit pull request #137
Opened 2022-08-01 15:03 UTC by parthdhanjal

Description

Add Github Action to verify the title so that we can generate the release notes

Closes: https://github.com/operator-framework/audit/issues/133

2022-08-01 15:05 UTC, camilamacedo86 commented on .github/workflows/TitleVerifier.yaml
> +        github_token: ${{ secrets.GITHUB_TOKEN }}
Could give an space at the end of this file?

2022-08-01 15:06 UTC, camilamacedo86 commented on .github/workflows/TitleVerifier.yaml
> +
Could you please rename the file for we do not have capitalized letters? 
For example, could it be title-verify.yml

2022-08-01 20:04 UTC, gallettilance requested changes
Please squash the commits

2022-08-02 08:41 UTC, camilamacedo86 commented on .github/workflows/TitleVerifier.yaml
> +        github_token: ${{ secrets.GITHUB_TOKEN }}
done

2022-08-02 08:41 UTC, camilamacedo86 commented on .github/workflows/TitleVerifier.yaml
> +
done

2022-08-02 10:51 UTC, merged